services:
  fastapi:
    build: ./fastapi
    platform: linux/amd64
    container_name: fastapi
    networks:
      - predictor_net

  streamlit:
    build: ./streamlit
    container_name: streamlit
    networks:
      - predictor_net

    
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80" #map nginx:80 to the localhost:8080 (only gateway to outside)
    depends_on:
      - fastapi
      - streamlit
    networks:
      - predictor_net

networks:
  predictor_net:
    driver: bridge
