events {}

http {
    server {
        listen 80;

        # Streamlit frontend
        location / {
            proxy_pass http://streamlit:8501/;

            #needs to be done to forward the websocket connection (not fully understood yet :D)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}